### ISSUE TITLE
Update startChatContactAPI - start-chat-contact.zip runtime

### ISSUE THREAD

**Issue by taylanu** [amazon-connect/amazon-connect-chat-ui-examples#114]
Issue:
Current runtime of ChatSDK Lambda layer is Node.JS 14.x
Location: Custom Lambda helper is located in "start-chat-contact-api-cfn" bucket.
`s3://start-chat-contact-api-cfn/deployment`

Solution:

Review `start-chat-contact.zip` custom Lambda function, update codebase to Node.JS 16.x
Update CloudFormation template to Node.JS 16.x runtime for the AWS Lambda function.
Reason:
Node.JS 14.x entered EOL April 30th, 2023.

It is no longer receiving security updates and is no longer being maintained.
Node.JS 14.x is still supported by AWS Lambda, but many companies have announced deprecation for the runtime.
Source: https://github.com/nodejs/release#release-schedule

**Comment by chaumdh** [comment]
Hi @taylanu, thanks for the flag. We are working on upgrading to NodeJS 18.x!

**Comment by spencerlepine** [comment]
`CloudFormation.yaml` has been updated, stack can now be deployed after changes raised in https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/124
