### ISSUE TITLE
Disable/Remove console logs

### ISSUE THREAD

**Issue by adesheddie** [amazon-connect/amazon-connect-chat-ui-examples#12]
Is there any way to disable all the console logs once the chat starts?

**Comment by efh365** [comment]
No, we currently don't have that functionality. I will look into adding it for a future release.

**Comment by efh365** [comment]
You can disable console logs if you use the open source version of chat-interface-js. If you follow the build steps for prod it removes the console logs. https://github.com/amazon-connect/amazon-connect-chat-interface
