### ISSUE TITLE
Uncaught ReferenceError: enableAttachments is not defined

### ISSUE THREAD

**Issue by turik97** [amazon-connect/amazon-connect-chat-ui-examples#127]
Hi, I'm doing everything from this example - https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/public/index.html and getting a syntax error in console. 

![image](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/22335853/c36b8eab-250e-4e17-bf4f-9017ebe92448)

**Comment by spencerlepine** [comment]
Hi @turik97, it looks like the a bug was introduced in the last update to `ACChat.js` file. This should be resolved in https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/123, but that is still in review.

Can you try using the this `ACChat.js` file instead? https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/cf580474d09db4bf4d3b4d2c8c5e48e3609a56a0/customChatWidget/public/ACChat.js

Alternatively, you may be able to work-around this issue for now by creating a global variable:

```diff
// https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/public/index.html

<body>
    <div id="root"></div>
    <script src="amazon-connect-chat-interface.js"></script>
+ <script>
+      var enableAttachments = false; // or true
+
+    // OR: window.enableAttachments = false
+   </script>
    <script src="ACChat.js"></script>
    <script>
         AmazonCustomChatWidget.ChatInterface.init({ })
        // ...
    </script>
</body>
```

**Comment by mliao95** [comment]
Closing issue.  Please re-open if you are still experiencing any issues.

**Comment by mliao95** [comment]
Re-opening to track PR #123
