### ISSUE TITLE
Any way to create a component with reactJs?

### ISSUE THREAD

**Issue by mtzluis** [amazon-connect/amazon-connect-chat-ui-examples#13]
I am trying to create a component in reaction, but I have an error in initialization.
What is the best way to import `js / amazon-connect-chat-interface.js`?
````````
  componentDidMount() {
    this.initChatInterface();
  }

  initChatInterface = () => {
    // this.connect = window.connect;
    connect.ChatInterface.init({
      containerId: 'root',
    });
  }

**Comment by angieyu** [comment]
@mtzluis when you console log window.connect, what does it return?
