### ISSUE TITLE
Get Error code 403 access denied 

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-chat-ui-examples#133]
After submit the form i get the response from lambda and i got following error when hit this API endpoint 
`https://participant.connect.us-east-1.amazonaws.com/participant/connection`
![image](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/110086158/fe13bf7a-f62a-4339-8a59-d9f2093d1b42)
I verified the headers, signature and Participant token passed successfully to the request headers. Can anyone please guide me that what should i do to resolve this issue.

**Comment by doreechi** [comment]
Hi, can you provide the network HAR for this? Or more details on how the request was formed. Also, where was the participant token was attained from? If you also provide some contactIds, I can look into service logs.

**Comment by doreechi** [comment]
Hi, from service logs I see that the error is that the chat that you are trying to connect to has already been terminated. Can you try starting a fresh chat and making the CreateParticipantConnection with those new details?

**Comment by SaqibOctave** [comment]
hi @doreechi, 
I tried a lot of time to start the chat but everytime i got the same error Access denied, I am not creating the CreateParticipantConnection by my self it is creating when we get the 200 response from lambda, AmazonCustomChatWidget.ChatInterface.init this method internally call the CreateParticipantConnection API. and i got the error Access denied. Please help me to resolve this

**Comment by doreechi** [comment]
Whenever you are calling startChat, are you always receiving back the same contactId/participantId?? Can you try to remove ClientToken from the request?

**Comment by SaqibOctave** [comment]
Thank you @doreechi it works for me thanks a lot man
