### ISSUE TITLE
amazon-connect-chat-interface.js uses new Function which throws CSP error

### ISSUE THREAD

**Issue by efowler2** [amazon-connect/amazon-connect-chat-ui-examples#137]
amazon-connect-chat-interface.js uses a line **new Function** for a string, and this is not allowed with servers that have CSP enabled. Is this something that can be fixed to use a more secure way?

`try {
                    r = r || new Function("return this")()
                } catch (e) {
                    "object" == ("undefined" == typeof window ? "undefined" : n(window)) && (r = window)
                }
                e.exports = r`

**Comment by mliao95** [comment]
Hey @efowler2!

This code is actually webpack code that is bundled within our `amazon-connect-chat-interface.js` file. This is a duplicate issue as: https://github.com/webpack/webpack/issues/6461

Let me know if you need anything else.  Thanks!

**Comment by efowler2** [comment]
Thank you!

We use a third-party to build and standardize our website. We don't have many options to change the code for web.config.js. Is there a way to comment out this new Function line to have the chat bot work? I keep trying different variations, and get different errors.

**Comment by mliao95** [comment]
Hey @efowler2 ,

I managed to build a version of `amazon-connect-chat-interface.js` without that line, however, you're going to have to fork [amazon-connect-chat-interface](https://github.com/amazon-connect/amazon-connect-chat-interface) and make a change to the webpack file.

1. Clone [amazon-connect-chat-interface](https://github.com/amazon-connect/amazon-connect-chat-interface)
2. Modify [./configuration/webpack.config.{dev/prod}.js](https://github.com/amazon-connect/amazon-connect-chat-interface/tree/master/configuration) to include `global: false` inside [this node object](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/configuration/webpack.config.prod.js#L517)
3. run `npm run release` to build a production minified file or `npm run dev-build` to produce a readable bundled file
4. Either way, you can find the `amazon-connect-chat-interface.js` file under `./build/dist/static/js/amazon-connect-chat-interface.js`

If you use this new minified file, it should avoid the CSP issues you're running into.  Let me know if that works for you.

**Comment by mhiaror** [comment]
Hi @efowler2 

It is expected that you will face this error (global not defined) if we follow the solution provided by webpack https://github.com/webpack/webpack/issues/6461#issuecomment-394318550
https://github.com/webpack/webpack/issues/5627#issuecomment-394309966
https://github.com/embroider-build/ember-auto-import/issues/50 - has a good suggestion too but slows down the build time. 

Can you please follow the solution provided by webpack team in the ticket.
