### ISSUE TITLE
Source files for amazon-connect-chat-interface.js

### ISSUE THREAD

**Issue by JakeScheller** [amazon-connect/amazon-connect-chat-ui-examples#14]
First off, thanks a bunch for providing this example implementation. It's really helped my team get off the ground much quicker than we otherwise could.

I love the asyncCustomerChatUX widget, but I'd like to be able to modify it a little to work better for my team's needs. It looks like amazon-connect-chat-interface.js defines the React components that render the widget. Would it be possible for you to open-source the unminified files you used to compile that?

@efh365 mentioned back in December on issue #3 that this was in the works but at that point there wasn't a timeline for it. Is there any update on this? I really want to use your widget as a good foundation instead of building my own.

**Comment by efh365** [comment]
Hi Jake,

I'm glad it has been a help for you! We are still looking into open sourcing it, but do not have any timeline for that.

**Comment by JakeScheller** [comment]
Alright, thanks for the update!

**Comment by efh365** [comment]
We have open sourced the interface.js file - https://github.com/amazon-connect/amazon-connect-chat-interface
