### ISSUE TITLE
Cannot create amazon-connect-interactive-messages-example stack because of the Lambda runtime version

### ISSUE THREAD

**Issue by ChamseddineBhd** [amazon-connect/amazon-connect-chat-ui-examples#169]
samTemplates/amazon-connect-interactive-messages-example/template.yaml needs to be updated.

Proposed update L27:
Runtime: nodejs12.x ==> Runtime: nodejs18.x
nodejs12.x is deprecated since  Mar 31, 2023.

Source: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by spenlep-amzn** [comment]
Hi @ChamseddineBhd, thank you for raising the issue. Team is are currently tracking this in our backlog, we do not have an ETA for the fix.

In the meantime, you can still create a lambda function and import a .zip folder with the nodejs code: 
1. Create a lambda function ([Documentation](TODO))
2. Find the "Upload from" dropdown, and select ".zip file"
3. Download the lambda zip: [interactive-messaging-lex-codehook.zip](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/spenlep/do-not-delete-until-2025-lambda-zip/samTemplates/amazon-connect-interactive-messages-example/interactive-messaging-lex-codehook.zip) (source: [branch](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/spenlep/do-not-delete-until-2025-lambda-zip))
4. Import the lambda
5. Proceed to Lex Bot console, and associate your Lambda to the bot

>// internal ref
> ui-example: [samTemplates/amazon-connect-interactive-messages-example](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/samTemplates/amazon-connect-interactive-messages-example)
>Source: https://serverlessrepo.aws.amazon.com/applications/us-west-2/841676849665/amazon-connect-interactive-messages-example
>(Old) Lex v1 Blog Post: https://aws.amazon.com/blogs/contact-center/easily-set-up-interactive-messages-for-your-amazon-connect-chatbot/

**Comment by spenlep-amzn** [comment]
**Update:** working on upgrade in https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/186. 

The new samTemplate has been published for both Lex V1 and Lex V2:

- Lex V1: https://serverlessrepo.aws.amazon.com/applications/us-west-2/533267401313/amazon-connect-interactive-messages-example-lex-v1
- Lex V2: https://serverlessrepo.aws.amazon.com/applications/us-west-2/533267401313/amazon-connect-interactive-messages-example-lex-v2

**Comment by spenlep-amzn** [comment]
@ChamseddineBhd
