### ISSUE TITLE
Api Gateway response MissingAuthenticationTokenException.

### ISSUE THREAD

**Issue by hiteshbhattarai** [amazon-connect/amazon-connect-chat-ui-examples#17]
We are using AuthorizerLambdaFunction with CognitoUserPool to authorize ApiGateway. While trying initiateChat with apiGatewayEndpoint, we are receiving MissingAuthenticationTokenException. We have implement a way to get accesstoken from UserPoll but how do we pass while initiateChat. Or I am not sure if I am doing somethign wrong.

One more question, we already have amazon connect running and is being used in salesforce, do i have to run this cloudformation template to implement chat feature?

 Please help.

**Comment by efh365** [comment]
Hi Hitesh,

Is this for the async chat solution with the pre-built widget? I don't believe you can use an authorizer lambda function with the widget as the underlying call to API Gateway will need to have a signature change for that functionality.

For your second question, no, you don't need to run this template to implement chat. These templates are here to help get you started with the customer side implementation, but are not a requirement by any means.

**Comment by hiteshbhattarai** [comment]
Hi,
  Thanks for the help. I was able to get asyncCustomerChatUX running. 

But I am still facing one final issue, First time initiateChat  goes well, But second time if we try to initiateChat  we are facing Initiazilation failed error. Prod api returns successfully new token but next call fails even its using new token. It happen lots of time.
![2020_05_12_17_20_43_Settings](https://user-images.githubusercontent.com/17991750/81751420-fc67ce00-9474-11ea-8810-0ffe2b3b607a.png)

**Comment by efh365** [comment]
Please make sure your S3 trigger is set up properly. Once a call is over the transcript is put in S3. That event marks the chat as complete in the DDB table. If the chat is not marked as complete, the previous chat's connection token is returned and there is 403 establishing the chat when talking to ACPS.
