### ISSUE TITLE
urlPreviewForAsyncChat requires updates

### ISSUE THREAD

**Issue by Onolisk** [amazon-connect/amazon-connect-chat-ui-examples#170]
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/urlPreviewForAsyncChat 

The above template was last modified three years ago. Since then security posture has changed for various services and the template is no longer depoyable as is. Changes include:

- S3 now disables ACLs by default
- Lambda nodejs12 deprecated

Please assist in updating the template so that it can be used going forward, or making the repo private to avoid any failed deployments

**Comment by spenlep-amzn** [comment]
@Onolisk , .A new template has been published, working on merging #191 (not sure if the old .yaml template was properly updated)


|  Region | Launch Button |
| ------ | ------------- |
| us-east-1 (N. Virginia) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3.amazonaws.com/us-east-1.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| us-west-2 (Oregon) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://us-west-2.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-us-west-2.amazonaws.com/us-west-2.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| ap-southeast-2 (Sydney) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://ap-southeast-2.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-ap-southeast-2.amazonaws.com/ap-southeast-2.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| ap-northeast-1 (Tokyo) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://ap-northeast-1.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-ap-northeast-1.amazonaws.com/ap-northeast-1.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| eu-central-1 (Frankfurt) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://eu-central-1.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-eu-central-1.amazonaws.com/eu-central-1.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| eu-west-2 (London) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://eu-west-2.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-eu-west-2.amazonaws.com/eu-west-2.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| ap-southeast-1 (Singapore) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://ap-southeast-1.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-ap-southeast-1.amazonaws.com/ap-southeast-1.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| ca-central-1 (Canada) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://ca-central-1.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-ca-central-1.amazonaws.com/ca-central-1.amazon-connect-url-preview-cfn/cloudformation.yaml) |
| ap-northeast-2 (Seoul) | [![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://ap-northeast-2.console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=urlPreviewForAsyncChat&templateURL=https://s3-ap-northeast-2.amazonaws.com/ap-northeast-2.amazon-connect-url-preview-cfn/cloudformation.yaml) |
