### ISSUE TITLE
asyncCustomerChatUX widget unable to display Lex Prompt response cards.

### ISSUE THREAD

**Issue by hiteshbhattarai** [amazon-connect/amazon-connect-chat-ui-examples#18]
Hi, We have integrated Lex with chat  and its displaying slots prompt in chat widget but it doesnot display slots prompt response cards  as a option in widget. How can we achieve that. We want user  to select those options. Any help would be greatly appreciated.

**Comment by efh365** [comment]
Hi. Currently the widget does not integrate with Lex response cards. If you want to give the customer options to select from Lex, you will need to build your own customer chat implementation. You can send a message to the customer through Amazon Connect as a JSON blob and then in the customer chat implementation you can parse that JSON and render it as a list picker.

**Comment by dfw100** [comment]
Hoping you were able to get past this using information provided by efh365. Closing this issue; please reach out if you need additional information.
