### ISSUE TITLE
Unable to remove preChat form from customChatWidget

### ISSUE THREAD

**Issue by tisdaled** [amazon-connect/amazon-connect-chat-ui-examples#181]
Hello,

We are implementing the customChatWidget in our Salesforce customer portal which starts the AWS Connect Chat.  We do not want to use the preChat form - just have the chat window load when the chat icon is selected.  When the value under preChatForm for visible is changed to false, the chat icon fails to load.  Are there other places in this setup where the preChat form needs to be disabled and still have the chat icon be displayed?

**Comment by xiajon** [comment]
If you do not want the pre chat form, we recommend the Amazon Connect Chat Interface example as a starting point. https://github.com/amazon-connect/amazon-connect-chat-interface.

**Comment by tisdaled** [comment]
Thanks for your feedback - We have to use this code because we are using Salesforce Lightning as the place where the widget code is hosted.

There is a boolean value in index.html where it looks like we should be able to disable the preChat form
preChatForm: {
               visible: true,
When we set this value to false, the chat icon does not display.  This only happens after we run the npm run build process.  
Any additional help you can provide would be great.  Thanks!

**Comment by tisdaled** [comment]
The documentation shows there is supposed to be an option to not display the ChatForm.  
![PreChatForm](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/117933187/f569a88a-716a-4b5d-9811-d20f22cdaa13)
Changing this value to False, causes the chat icon to not load.  The best we have been able to do at this point is to eliminate the data entry fields in the PreChat form leaving just a blank window with a Submit button.  We only allow authenticated customers access to even get to the webpage where the chat widget is displayed so we have no need to collect name and email address or any other PreChat info.

Please let me know if this is something that can be fixed or if there is a better workaround.  Thanks!

**Comment by tisdaled** [comment]
I have been able to resolve this issue with help from our AWS team.  The following instructions allows the preChatForm to be disabled.

1.	Go to /customChatWidget/src/constants/index.js
2.	Add the following lines of code
export const chatWithoutFormStates = {
  FORM: 'form',
  CHAT_WIDGET: 'chat'
}
3.	Save and close the file
4.	Go to /customChatWidget/src/views/ChatWithoutForm/index.js 
5.	Update line 9 (or the line matching the import statement below) so it reads as follows:

import { device, loggerNames, chatInitiationIcon, chatWithoutFormStates } from '../../constants';
6.	On the same file, inside the “ChatWithoutForm” function (line 20 on mine), add the following:

const [currentState, setCurrentState] = useState(chatWithoutFormStates.CHAT_WIDGET);
7.	Save and build (npm run build)

**Comment by spenlep-amzn** [comment]
Hi, I have raised a PR for the fix, thank you for raising the issue!

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/192
