### ISSUE TITLE
Calling startChatContact Directly Via AWS SDK for JavaScript

### ISSUE THREAD

**Issue by vitalyper** [amazon-connect/amazon-connect-chat-ui-examples#19]
Can custom chat widget call directly without need for Lambda and API Gateway?
If yes, why API Gateway is required in your example.

**Comment by efh365** [comment]
Technically, yes you can make the call to start the chat without lambda and api gateway. however, to do so you will need to store your AWS credentials in your web application, which is not secure. That is why we use API Gateway instead.
