### ISSUE TITLE
PersistentChat on Page Refresh

### ISSUE THREAD

**Issue by outplex** [amazon-connect/amazon-connect-chat-ui-examples#210]
Hi team,

We have deployed this [customChatWidget ](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget)  solution and we're trying to achieve persistent chat sessions. For example, if a customer has an active conversation and refreshes the browser or switches to a different tab, they should return to the same existing conversation with the same representative and chat history.

We followed the steps listed on this article [Enable persistent chat ](https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html), and we managed to load the previous transcripts, however, a new conversation is started with a new representative. We would like to have the customer continue chatting with the same representative from the previous active conversation.

Is it possible?

Thanks for the support.

**Comment by mhiaror** [comment]
You can setup Agent queues to transfer to the same agent, its explained in the doc here https://docs.aws.amazon.com/connect/latest/adminguide/transfer-to-agent.html
