### ISSUE TITLE
iOS example missing .xcodeproj file 

### ISSUE THREAD

**Issue by smexic** [amazon-connect/amazon-connect-chat-ui-examples#216]
Hi, where can I find the .xcodeproj file?

**Comment by mrajatttt** [comment]
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/217

**Comment by mrajatttt** [comment]
Hi @smexic, changes have been merged.

**Comment by mliao95** [comment]
Closing issue.  Re-open if the issue persists.
