### ISSUE TITLE
IntiateChatFailure1 + InitiateChatFailure2

### ISSUE THREAD

**Issue by mTowers93** [amazon-connect/amazon-connect-chat-ui-examples#24]
Hi there,

I am trying to implement the chatui example and am experiencing two cases of chat initiation failures. 

What i've found is that the only way to get another chat to initiate is to delete the entry from dynamodb and then it works. Im not sure why but after the first chat it never creates another item in the DDB for the next chat and the current chat stays as the previous one.

The initiateChatFailure varies between 1 and 2. 

![Initialization failed connect](https://user-images.githubusercontent.com/22008112/93230524-0c235600-f778-11ea-9f64-2afccf86f380.PNG)
![Initialization failed console](https://user-images.githubusercontent.com/22008112/93230757-51e01e80-f778-11ea-81b1-f8876dfef91f.PNG)

**Comment by efh365** [comment]
Hi, please refer to the troubleshooting section on the readme: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX

This is mostly likely due to the S3 trigger not being set up properly

**Comment by khastation** [comment]
Are you still having this issue?

**Comment by efh365** [comment]
@mTowers93 are you still having this problem?

**Comment by kqia040** [comment]
Please feel free to re-open if you have still experiencing the same issue.
