### ISSUE TITLE
send x-api-key in request header

### ISSUE THREAD

**Issue by syanix** [amazon-connect/amazon-connect-chat-ui-examples#25]
Is there a way to send x-api-key in request header? (I have tried to guessing the parameter in initiateChat by adding parameters like accessKey, secretKey, clientConfig, but no luck.)

I can see in the minified amazon-connect-chat-interface.js file contains the keyword headers["x-api-key"], but it is difficult to find out what it does without source code.

@efh365  would you be able to share if it is possible to do?

**Comment by efh365** [comment]
Hi syanix. No, you are not able to send x-api-key in the request header right now. I will take note of this request and update you if we decide to add that functionality.
