### ISSUE TITLE
Cannot start second chat with same details

### ISSUE THREAD

**Issue by BrisbaneGamer** [amazon-connect/amazon-connect-chat-ui-examples#29]
Hi, I have an issue where once the chat is ended, it is uploaded to the S3 bucket, though I believe it is then not being updated in DynamoDB. The items in DynamoDB show nextContactId as set to 'CURRENT_CHAT' and previousContactId as set to 'INITIAL_CHAT', which I suspect is wrong.

I have seen that your troubleshooting area mentions to make sure the S3 trigger is set up properly - are you able to provide step by step instructions on how to do this please? I have made sure that AmazonConnectS3BucketName and transcriptPath are the same in Amazon Connect and CloudFormation.

My 'ConnectChatBot-UpdateDdbWithS3LocationLambda-' lambda function has no trigger added to it, is that the issue? If it is, what trigger should be added? Thanks.

**Comment by BrisbaneGamer** [comment]
Upon further inspection, I think the issue may be the event on the S3 bucket. I presume that this should be set to Lambda function / 'ConnectChatBot-UpdateDdbWithS3LocationLambda-', though which events should be ticked?

**Comment by BrisbaneGamer** [comment]
PUT + Lambda Function +  'ConnectChatBot-UpdateDdbWithS3LocationLambda-' as an Event on the S3 bucket appears to have resolved the issue.

**Comment by robmoores** [comment]
I know this is closed but if someone has a similat issue this is what the trigger on the S3 transcripts bucket should look like:
•	Event type: ObjectCreated
•	Notification name: Yssje6d8djx8w8wjs8xWUtMzAwYjdhMDQyNmI5
•	Prefix: connect/whatever/ChatTranscripts
