### ISSUE TITLE
Web preview not displaying

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-ui-examples#32]
Installed via Cloudformation stack in us-east-1. All works fine apart from no preview. I return some text that contains a valid URL eg https://bbc.co.uk . The URL is recognised as such (different colour, underlined) and clickable however there is no preview when I hover over the link (or any other time). Unsure if its relevant but two other messages are (intentionally) generated by the bot after the one that contains the link .The related Dynamo DB caching table is empty. Tested in Chrome and Edge. If there is anything else I can tell you please let me know (but please spell it out in simple terms as I'm still a novice !) Thanks.

**Comment by khastation** [comment]
hi @robmoores 
I can see the url preview in the chat for http://bbc.com and https://bbc.co.uk/. This process looks up for a webpage on the first attempt, fetches open graph metadata, saves it it Amazon DynamoDB for future reference, and renders it as a response card. 

The website you mentioned does not return a valid [open graph](https://ogp.me/) image, so you see the returned metadata displayed (formatted URL, short URL, and website description). 
![urlPreview-example](https://user-images.githubusercontent.com/40148037/97368168-95de3d00-1867-11eb-9160-b4d58b8da1ed.png)

I'm able to see the bbc website data populated as well. 
![urlPreview- database](https://user-images.githubusercontent.com/40148037/97368574-785da300-1868-11eb-86a1-3587264bfb58.png)

Can you confirm the response for the getUrlPreview network request in your browser console? It should look like the following:
![bbc-response](https://user-images.githubusercontent.com/40148037/97368842-fde15300-1868-11eb-8c33-8cd4feb7cadf.png)

Also, we do not support a hover preview functionality for this code at the moment.

**Comment by robmoores** [comment]
Thanks for your reply - it looks as though the URL has to be the only content in the response. Is that correct ?

**Comment by robmoores** [comment]
Regarding the response for the getUrlPreview network request in my browser console. This is what I see - can ypu please advise how I show the correct details ? Thanks :-)

![image](https://user-images.githubusercontent.com/53277403/97807399-61e48c80-1c58-11eb-912d-5364d88d217e.png)

**Comment by efh365** [comment]
Just to clarify here - I see that you are getting a 4xx to getUrlPreview, but I see that the preview is successfully displayed in the widget. Are you asking why the 4xx is being returned and if there should be different functionality?

**Comment by robmoores** [comment]
Hi efh3653 - I wasn't asking about the 4xx - but since you have mentioned it I am curious and keen to learn, if you have the time to explain !

In khastation's earlier reply they said "Can you confirm the response for the getUrlPreview network request in your browser console?" However I could not find how to display the screen he shows above so was just asking for instructions on how to find that screen. If you can help with that it will be appreciated. Thanks for replying. Rob.

**Comment by efh365** [comment]
I see. From your screenshot, you are almost there. You opened the right tab, but you have to open it before the request is made. If you open it afterwards, you wont see the result. So if you can open the console before you start the chat, that will help

**Comment by robmoores** [comment]
Hi efh. doh - so much to learn ! I'll have to do this tomorrow (UK) evening now. Thanks for the tip :-)

**Comment by robmoores** [comment]
Hi. Apologis for delay in coming back on this. I think it is working ok. From what I can understand the URLPreviewLambda parses the response back to the user looking for a URL. If it doesnt find one then fine...if it does then it has to be the only string returned and there can only be one URL . That works ! Thanks.
