### ISSUE TITLE
S3 Issue with London Preview URL Stack 

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-ui-examples#33]
When initiating the stack in the London region I (and my colleague) keep hitting an S3 error. I have checked in Frankfurt, N.Virginia and Oregon and there is no issue - just London  eu-west-2.

The error appears very early - I click on the NEXT button in the screen below and the error message appears as per the screenshot

![image](https://user-images.githubusercontent.com/53277403/97800348-790d8500-1c2c-11eb-83d2-5e9f2868ca52.png)

Any help appreciated !

**Comment by efh365** [comment]
Sorry the resource was not public. I just updated it. Can you try again?

**Comment by robmoores** [comment]
Hi efh365 - phew I thought it was me being dense ! Yes I will try again but what you say above makes sense so I an sure it will work . Many thanks. Rob
