### ISSUE TITLE
Customer Chat in iframe

### ISSUE THREAD

**Issue by RatnaVallabhaneni-wisc** [amazon-connect/amazon-connect-chat-ui-examples#35]
We are implementing the amazon connect streams API on a project. I used the connect.ChatInterface.initiateChat and it works fine in a separate popup window as the amazon connect contact Control panel. 

I wanted to implement the customer chat on the iframe so that it can be implemented in the layout page and be used through out the application. My problem here is when i reload the page, the existing customer chat is losing its session and its starting a new Chat. Can you provide me a example of the customer chat that can be used in all the pages of the application with out losing the Existing Chat session as shown in the attached image?

![AmazonConnect](https://user-images.githubusercontent.com/74385689/99011911-c8985e80-2512-11eb-8522-94b6bb25fcab.png)

**Comment by efh365** [comment]
Hi Ratna. This cloudformation template describes how to get the chat to persist through page refreshes: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX

**Comment by RatnaVallabhaneni-wisc** [comment]
Thanks for the reply. We're using the startChatContactAPI. Does your suggestion changes since, we're using the startChatContactAPI.

For Reference, we're using the below example:
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI

**Comment by efh365** [comment]
The startChatContactAPI repo simply triggers the start chat contact API, while the asyncCustomerChatUX also deploys a ddb table, an S3 trigger, and more involved code that keeps track of active chats and rehydrates existing ones instead of always starting a new one. Please refer to the readme in that repo to understand how it works and so your customer can pick up where they left off

**Comment by RatnaVallabhaneni-wisc** [comment]
Thanks. The asyncCustomerChatUX worked out and it is working as expected and we were able to keep the Chat on the reload. Is there any method that invokes the Disconnect customer chat, so that can be used on Window Close(as same functionality that end chat button click does)?
