### ISSUE TITLE
Agent name 

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-ui-examples#37]
Maybe more of a question than an issue - though may be the root cause of an issue....why does the test web page ask for a username and agent name ? Does it use these ? What if a agent name is specified that doesn't exist ? I've tried following the code and just can't see where these are used (but them I admit to being a noob). I've spent many hours poring over the stack and code and feel that I could contribute in some [small] way ... if you can help me to help everyone else that would be great !

**Comment by angieyu** [comment]
Hey @robmoores, the username and agent name are sent as parameters to the start chat API Gateway call, then used by the Lambda, and written to the DynamoDB to track chat instances. They are also passed into the Amazon Connect SDK (called from the Lambda) to use in the contact flow. 

As for the agent name, if it exists or not, that logic is handled in the routing logic in the contact flow. Potentially if the agent doesn't exists, you could send a prompt back to the user that the agent is offline or default to any agent that is currently online.

**Comment by robmoores** [comment]
Hi @angieyu Thanks for replying. I can see now that they are passed in the startChatContact as Attributes customerName and username. I will try picking those up in the Connect flow. I hadn't seen why the Agent name was requested but now understand its purpose - thank you :-)
