### ISSUE TITLE
Initialization sometimes fails due to embedded invokeUrl?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-chat-ui-examples#4]
Every once in a while our demo chat client fails when we load the page:

<img width="632" alt="Screen Shot 2019-12-23 at 12 02 21 PM" src="https://user-images.githubusercontent.com/127062/71378328-372ba100-257c-11ea-862e-af3353e51653.png">

Looking at the dev console, it shows a 403 connection error to: `https://4agcjusx3k.execute-api.us-east-1.amazonaws.com/prod/participant/connection`

The request being sent that yields the 403 is:

`{"Type":["WEBSOCKET","CONNECTION_CREDENTIALS"]}`

This Lambda function is not ours, so I checked amazon-connect-chat-interface.js, and it's embedded in there being set on a variable called `invokeUrl` for `us-east-1`:

```javascript
d = {
    "us-west-2": {
        invokeUrl: "https://eap1w93j0k.execute-api.us-west-2.amazonaws.com/prod"
    },
    "us-east-1": {
        invokeUrl: "https://4agcjusx3k.execute-api.us-east-1.amazonaws.com/prod"
    },
    "ap-southeast-2": {
        invokeUrl: "https://v4u8oq0cve.execute-api.ap-southeast-2.amazonaws.com/prod"
    },
    "ap-northeast-1": {
        invokeUrl: "https://3fidunfyz7.execute-api.ap-northeast-1.amazonaws.com/prod"
    },
    "eu-central-1": {
        invokeUrl: "https://1gynaarm3e.execute-api.eu-central-1.amazonaws.com/prod"
    }
}
```

Any idea what this is, or why it's being invoked only every once in a while?

**Comment by MattDN93** [comment]
Looks like these API Gateway API endpoints behave the same as the ACPS (Amazon Connect Participant) API endpoint.

If you call [CreateParticipantConnection](https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_CreateParticipantConnection.html) and instead of using ```https://participant.connect.us-east-1.amazonaws.com/participant/connection``` you use ```https://4agcjusx3k.execute-api.us-east-1.amazonaws.com/prod/participant/connection```
with:

```
{"Type": ["CONNECTION_CREDENTIALS", "WEBSOCKET"]}
```

And the correct ParticipantToken, you'll get back the WSS URLs and tokens just like the named endpoint.

**Comment by MattDN93** [comment]
Side note - check if when the error occurs, the API deployed in your own account is returning a new ParticipantToken - if the same / a cached ParticipantToken is returned, the ACPS API responds with a 403.

**Comment by winzig** [comment]
@MattDN93 Thanks Matt. I'll look into that. If it is, how would we resolve the underlying issue? Currently we're just using the Lambda functions provided as part of this repo.

**Comment by efh365** [comment]
Hi @winzig, thanks for reaching out. Can you try to download the most recent version of amazon-connect-chat-interface.js? It was just uploaded last week. We realized it was using an older version of ChatJS that did not properly destroy a websocket connection after a chat disconnects via API (either using the disconnect block or calling StopContact()). The subsequent chat started after ending the previous chat via API would see that error. Let me know if you continue to see the same error after using the new interface.js file.

**Comment by winzig** [comment]
@efh365 I'll check but I think I did integrate that last week. However, when we are seeing this is typically during testing, after letting the chat sit for a while, and then hitting reload on the page that starts the chat back up again. Do we need to make a specific call in the JS when someone is reloading (or otherwise exiting) the page?

**Comment by winzig** [comment]
@efh365 Confirmed we have the latest. Also appears I was wrong on the circumstances leading up to the error. It's happening after we call the internal `endChat` function directly to end the chat, and then we reload the page and re-init the chat, and we get this error. 

The reason we're calling endChat internal method directly is because we're putting an End Chat button in a different place in the UI than the one you're using in the footer of the sample async chat UI. The way we're currently doing this is by retaining a pointer to the function in the `footerConfig` render method:

```js
connect.ChatInterface.init
({
    containerId: 'chat-root',
    headerConfig: {
        isHTML: true,
        render: function(e) {
            return  `<div class="header-wrapper">\
                <h2 class="welcome-text">Chat Support</h2><button class="btn btn-sm" id="end-chat">End Chat</button>\
            </div>`;
        }
    },
    footerConfig: {
        isHTML: true,
        render: function(endChat) {
            mynamespace.chat.End = endChat.onEndChat; // Store a pointer to the "end chat" function for later
            return ''; // don't render a footer area
        }
    }
});
```

Then we bind our custom `End Chat` button to that function we saved in the `render()` method. This was the only way we could figure out to call directly into the End Chat functionality, so if there's an easier way, that would be appreciated. Especially since the way we're doing it doesn't seem to disconnect the web socket. Since when we use the default "End Chat" button, we don't see this Initialization Failed error.

**Comment by winzig** [comment]
@efh365 I take it back, I now am thinking we did not have the new JS code you put in place last week, and I think the issue is now resolved. It's hard to tell for sure because the code is all minified as you know. 

I'm going to close this as I think my issue is resolved, but if you know of a way to officially end the chat using the sample chat client so that we don't need to use my hack above, that would be great, thanks.

**Comment by ashokdevlabs** [comment]
Trying to connect connectParticipant service using aws-sdk but it giving error like below.

TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_5___default.a.ConnectParticipant is not a constructor

Please find the sample request below.
var params = {
ParticipantToken: ParticipantToken, // ParticipateToken from StartContactChat response
Type: [
"WEBSOCKET","CONNECTION_CREDENTIALS"
]
};

var connectparticipant = new AWS.ConnectParticipant({apiVersion: '2018-09-07'});

    connectparticipant.createParticipantConnection(params, function(err, data) {
      if (err) console.log(err, err.stack); 
      else     console.log(data); 
    });
Could anyone help me with an example to resolve this issue.
