### ISSUE TITLE
Cors errors occured when we created request to 'https://participant.connect.us-west-2.amazonaws.com/participant/connection'

### ISSUE THREAD

**Issue by ashokdevlabs** [amazon-connect/amazon-connect-chat-ui-examples#43]
Hello, We are trying to add asyncCustomerChatUX chat to a custom website and facing the above CORS issues. As part of adding chat widget to custom website i have done below things.

1. We have added website Url to initiateChatLambda function
2. We have created S3 bucket to host static website and imported 'amazon-connect-chat-interface.js'

we are using region "us-east-1" but i am not sure why this js is picking region as "us-west-2" and i am getting below error 

"Access to XMLHttpRequest at 'https://participant.connect.us-west-2.amazonaws.com/participant/connection' from origin 'https://XX-XXXXX-XXXX.s3.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Could you please help on this issue.

**Comment by angieyu** [comment]
Hi, can you try adding the URL that your widget lives on to the "Approved origins" tab on the Connect console?

**Comment by robmoores** [comment]
Hi @angieyu The straneg thiung is that *everything* lives on us-east-1. Just can't understadn the reference to us-west-2. I;ve looked in the amazon-connectchat-interface.js and there are only two references to regions names: 
            "us-west-2": {
                invokeUrl: "https://participant.connect.us-west-2.amazonaws.com"
and here:
"us-west-2/s3": "s3signature",

that .js file is way beyond my pay grade bur I can't see how us-west-2 is releavt at all! Any clues appreciated !

**Comment by Typhon66** [comment]
Hey @angieyu I'm having this exact same problem now. I have made no changes to the code or the template and just following the README, when using the cloudfront url provided i get this error when attempting to start a chat:

```
{
  "_debug": {
    "reason": "Failed to fetch connectionDetails with createParticipantConnection",
    "_debug": {
      "type": "AccessDeniedException",
      "message": "Access denied",
      "stack": [
        "AccessDeniedException: Access denied",
        "    at Object.extractError (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:780663)",
        "    at constructor.extractError (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:785835)",
        "    at constructor.callListeners (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:803503)",
        "    at constructor.emit (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:803214)",
        "    at constructor.emitEvent (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:796908)",
        "    at constructor.e (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:792448)",
        "    at r.runTo (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:830039)",
        "    at https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:830244",
        "    at constructor.<anonymous> (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:792736)",
        "    at constructor.<anonymous> (https://{cloudfrontURL}.cloudfront.net/js/amazon-connect-chat-interface.js:1:796963)"
      ]
    }
  },
  "connectSuccess": false,
  "connectCalled": true,
  "metadata": null
}
```

I have made sure that the URL origin is allowed in the amazon connect panel as well as making sure all the IAM roles have permission to access Amazon Connect. Not sure what else might be missing.

**Comment by kqia040** [comment]
Hey @robmoores can you check your Index page, there is a line that initiates the chat interface with a region. Could you check that it is us-east-1?

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/cloudformationTemplates/asyncCustomerChatUX/website/index.html#L286

**Comment by kqia040** [comment]
Hey @Typhon66 is your request making pass the CORS issue? The access denied could be due to different issues. The CreateParticipantConnection API takes in a few parameters, are you able to call this API manually to check if the credentials are valid?

https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_CreateParticipantConnection.html

**Comment by robmoores** [comment]
Hi @kqia040 kqia0 - ref: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/issues/43#issuecomment-741496900 
Yes it does:
					connect.ChatInterface.initiateChat({
						name: "Customer",
						username: "User1",
						region: "us-east-1",
						apiGatewayEndpoint: "https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/Prod",
						contactAttributes: JSON.stringify({
							"customerName": "Customer"
						}),
						contactFlowId: "xxx",
						instanceId: "xxx"
					}, successHandler, failureHandler)

For information, we switched to use the basic ChatUX rather than the one with the URL handling, and we no longer get this issue

**Comment by khastation** [comment]
@robmoores thanks for the confirmation that you were able to fix your issue.

**Comment by ashokdevlabs** [comment]
@kqia040 @angieyu  I am  trying to connect connectParticipant service using aws-sdk but it giving error like below.

TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_5___default.a.ConnectParticipant is not a constructor

Please find the sample request below.
var params = {
ParticipantToken: ParticipantToken, // ParticipateToken from StartContactChat response
Type: [
"WEBSOCKET","CONNECTION_CREDENTIALS"
]
};

var connectparticipant = new AWS.ConnectParticipant({apiVersion: '2018-09-07'});

    connectparticipant.createParticipantConnection(params, function(err, data) {
      if (err) console.log(err, err.stack); 
      else     console.log(data); 
    });
Could anyone help me with an example to resolve this issue.
