### ISSUE TITLE
asyncCustomerChatUX - The specified bucket does not exist - error

### ISSUE THREAD

**Issue by psvGustavo** [amazon-connect/amazon-connect-chat-ui-examples#45]
Hello, first off thanks for the example and solution , the step by step is very well written.

I'm currently having an issue when i try to create the stack on the "Set Up Steps" part 2. When i try to run , it displays the error "The specified bucket does not exist". It does create it on the S3 Bucket list and some files are created but the error make the entire thing rollback.

What could i do in this situation?

Thanks for any assistance.

**Comment by adwonnacott** [comment]
Same here!

**Comment by artworx** [comment]
I'm having the same issue: 

![image](https://user-images.githubusercontent.com/1954578/105976400-ccab3580-6098-11eb-8532-a0935d2fa4c2.png)

**Comment by efh365** [comment]
Sorry for the delay here. @psvGustavo @adwonnacott can you please add a screen shot of the error and add more detail? Which specific resource fails due to the bucket not existing?

@artworx it seems like your error is different. Can you confirm that you are deploying the stack in eu-west-2 and the lambda function in question is in eu-west-2? That object is marked as public so you should have access to it.

**Comment by artworx** [comment]
@efh365 using the exact same settings `asyncCustomerChatUX` fails with the error above, `startChatContactAPI` deployed successfully.

**Comment by efh365** [comment]
Can you confirm the regions match correctly? That you are in eu-west-2 when you deploy the async chat solution

**Comment by artworx** [comment]
I used the "Launch Stack" button next to eu-west-2, hopefully, it sets the region correctly. 


> That object is marked as public so you should have access to it.

This is the behavior I'm seeing, which is consistent with the cloudformation error I've posted above. 

```
aws s3 cp s3://eu-west-2.amazon-connect-url-preview-for-async-chat-cfn/deployment/urlPreviewLayer.zip .           
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden        
```

```
aws s3 cp s3://us-east-1.amazon-connect-url-preview-for-async-chat-cfn/deployment/urlPreviewLayer.zip .   
Completed 17.5 MiB/19.3 MiB (389.5 KiB/s) with 1 file(s) remaining  
```

**Comment by efh365** [comment]
Oh wow thank you for the find! I saw the urlPreviewFunction.zip file in the eu-west-2 bucket but it looks like the Layer.zip file was missing. I just uploaded it and made it public. Please let me know if that fixed your problem
