### ISSUE TITLE
amazon-connect-chat-interface.js does not working in  Internet Explorer 11. 

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-chat-ui-examples#46]
Hello , 

Does anyone have any fix or Idea , why amazon-connect-chat-interface.js is not working in  Internet Explorer 11. 

![image](https://user-images.githubusercontent.com/1154682/103699941-8c084280-4f58-11eb-8f75-87ee0c63d760.png)

```
jQuery.Deferred exception: 'connect' is undefined ReferenceError: 'connect' is undefined
Object doesn't support property or method 'values'
```

**Comment by amicming** [comment]
I found this - https://stackoverflow.com/questions/44091075/script438-object-doesnt-support-property-or-method-values

Object.values() is not supported in Internet Explorer. - see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values#Browser_compatibility) for Object.values()

Is this going to fix soon?

**Comment by MattDN93** [comment]
Amazon Connect [does not support Internet Explorer at all](https://docs.aws.amazon.com/connect/latest/adminguide/browsers.html) for the softphone, and by extension the JS SDKs for manipulating chats and calls in that regard will not support IE and hence will probably never be "fixed". Suggest you use another supported browser instead, like Chrome, Firefox!

**Comment by efh365** [comment]
Yes, I am sorry but IE9 is not supported.

**Comment by amicming** [comment]
@efh365 , Did you see this - https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/50 ?

See 2nd point in PR description - Adds some styling fixes for IE 11

Can you please confirm? Is it not working in IE 9 or IE 11? I'm talking for IE 11 NOT IE 9

**Comment by efh365** [comment]
I spoke to the user who submitted that PR and he said the change he did was best effort for IE11, but IE11 is not officially supported by Amazon Connect.
