### ISSUE TITLE
Latest amazon-connect-chat-interface.js does not include URL preview feature

### ISSUE THREAD

**Issue by deepathakkar** [amazon-connect/amazon-connect-chat-ui-examples#48]
Is there a version of chat-interface.js that contains all latest features including urlpreview and interactive messages ?
Looking at file chat-interface.js from asyncCustomerChatUX and urlpreview they are not really from same master it seems. None of the files support both urlprevieiws and interactive messages.

**Comment by khastation** [comment]
@deepathakkar We've added support for attachments to the urlPreview solution. Let us know if you have any issues.
