### ISSUE TITLE
help resolving error

### ISSUE THREAD

**Issue by mtvmattwind** [amazon-connect/amazon-connect-chat-ui-examples#49]
Wed Jan 20 15:52:32 UTC 2021 : Endpoint response body before transformations: {"errorType":"TypeError","errorMessage":"Cannot read property 'Username' of null","trace":["TypeError: Cannot read property 'Username' of null","    at Runtime.exports.handler (/var/task/startChatContact.js:12:23)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

**Comment by efh365** [comment]
@mtvmattwind can you please add more information as to where you saw this error, which of few solutions you deployed, and if you made any modifications?
