### ISSUE TITLE
Better segregation of topics/steps in startChatContactAPI/README.md

### ISSUE THREAD

**Issue by ashakdhe** [amazon-connect/amazon-connect-chat-ui-examples#51]
Hello,

Here's some feedback revolving around the segregation of sections more clearly

- The "Prebuilt Chat Widget" section ends after point 3.  Right after, the next topic "## Create Your Own Chat UX" starts without any heading. Clear demarcation would be helpful here.
- We jump straight to point number 7 after point number 3.

**Comment by efh365** [comment]
Thank you for pointing out the styling bug! I just updated the readme
