### ISSUE TITLE
How to not loose chat on page refresh

### ISSUE THREAD

**Issue by Shubham-Pachade** [amazon-connect/amazon-connect-chat-ui-examples#52]
I am using a pre-built chat widget in **cloudformationTemplates/startChatContactAPI**. I have deployed the compete stack and I can now link it to my website users. But, the problem is when the user refreshes the page the chat session disappears and on clicking, **start chat** a new chat session is established? How do I retain my previous chat session even on events like page refresh?

**Comment by efh365** [comment]
Hi @Shubham-Pachade. We have another solution in this repo, the asyncChatSolution, that enables you to retain the session on page refreshes. Basically, it maintains open chat sessions in a DDB table and reestablishes the existing chat if there is one for the user. Please refer to the [README](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX) and let me know if you have any other questions.

**Comment by Shubham-Pachade** [comment]
Thank you so much. **asyncChatSolution** is exactly what I was looking for.
