### ISSUE TITLE
Conflict in AWS SDK and chat-interface.js

### ISSUE THREAD

**Issue by Shubham-Pachade** [amazon-connect/amazon-connect-chat-ui-examples#54]
The problem I am facing is, where to place "<script src="js/amazon-connect-chat-interface.js"></script>" in the code. Since if I keep this script tag above the AWS SDK import script tag (<script src="https://sdk.amazonaws.com/js/aws-sdk-2.769.0.min.js"></script>) then there is an error **TypeError: AWS.ConnectParticipant is not a constructor**. If kept below then error **Uncaught TypeError: AWS.DynamoDB is not a constructor** appears. So there seems to be a conflict in terms of where to place <script src="js/amazon-connect-chat-interface.js"></script> tag in the code. Please if anyone encountered the same issue, what could be the probable solution?

**Comment by mcosicaws** [comment]
`amazon-connect-chat-interface` has `amazon-connect-chatjs` as a dependency. 

The AWS-SDK is, by default, included in `amazon-connect-chatjs` as a "baked-in" dependency.
Please check `amazon-connect-chatjs` README: 
https://github.com/amazon-connect/amazon-connect-chatjs
There is a section that describes the correct import order. 
https://github.com/amazon-connect/amazon-connect-chatjs#scenario-4-chatjs-only-with-aws-sdk-import

Please let us know if that helps.

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
