### ISSUE TITLE
Getting Resource Not Found of type Null in response while starting the chat contact

### ISSUE THREAD

**Issue by ZeeshiM** [amazon-connect/amazon-connect-chat-ui-examples#55]
Can anyone help me resolve this error.

**caught error ResourceNotFoundException: Resource not found of Type: null**

i got this error while initiating the chat contact from my lambda function in amazon connect.

Object I'm sending to initiate the chat:

var startChat = {
            InstanceId: instanceId,
            ContactFlowId: conactflowid,
            Attributes: {
                "customerName": body.customerName,
                "firstName": body.firstName,
                "lastName": body.lastname,
                "Phone": SenderID,
                "message": body.Message,
                "channel": "FACEBOOK",
                "phoneNumber": SenderID,
                "username": body.username,
            },
            ParticipantDetails: {
                DisplayName: "FACEBOOK",
            },
        };
        // "Phone": body["Attributes"]["Phone"],
        console.log("Object-Compiled", startChat);
        **connect.startChatContact(startChat, function (err, data)** {
            if (err) {
                console.log("Error starting the chat.");
                console.log(err, err.stack);    // This is where I'm getting error.
                reject(err);
            }
            else {
                // console.log("Start chat succeeded with the response: " + JSON.stringify(data));
                resolve(data);
            }
        });
    });

**Comment by mcosicaws** [comment]
Could you please post here the output of this line: `console.log("Object-Compiled", startChat);`
Since it would be useful to see the exact parameters you're sending to Amazon Connect API.

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
