### ISSUE TITLE
Template Fails

### ISSUE THREAD

**Issue by cmrockwell** [amazon-connect/amazon-connect-chat-ui-examples#59]
Hi 
Just tried the startChatContactAPI cloud template. It failed with the following message

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: xxxxxxx, Extended Request ID: null)" (RequestToken: xxxxx, HandlerErrorCode: InvalidRequest)

**Comment by mcosicaws** [comment]
Thanks for letting us know, we are going to work on template updates, but in the meantime could you please try to update cloudformation.yaml by setting Lambda Runtime to nodejs14.x and test the deployment?

**Comment by khastation** [comment]
@cmrockwell release v1.2.3 addresses this issue, let us know if you have other questions.
