### ISSUE TITLE
cloudformationTemplates/asyncCustomerChatUX sample can't load transcript with same username

### ISSUE THREAD

**Issue by MichaelM193** [amazon-connect/amazon-connect-chat-ui-examples#65]
Does anyone meet the same issue, after deploy asyncCustomerChatUX template, use the same FirstName and UserName to login and load the Chat UI, there can't load the transcript but just start a new contact session.

**Comment by angieyu** [comment]
Hi, this is not an out of the box feature. You can find the previous transcript, attach it to the contact attribute, and pass it to the agent view to display.

**Comment by haomingli2020** [comment]
Hi, I want to share an update - on Feb 10, 2023 the [asyncCustomerChatUX](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX) was deprecated. 
Please switch to using the [startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI) template.

Closing the issue as there hasn't been new request. Feel free to reopen if more questions come up
