### ISSUE TITLE
Browser Notifcations

### ISSUE THREAD

**Issue by LahiruWijesuriya** [amazon-connect/amazon-connect-chat-ui-examples#66]
Do browser notifications need to be manually implemented in this repo? If so, how?

**Comment by fidel-tensoriot** [comment]
I managed to get the notifications working on my implementation on both the "CustomChatWidget" and the "connect-chat-interface"

You have to allow permission for the notification api by tying it into an event like a click.

**Comment by angieyu** [comment]
hi @LahiruWijesuriya, was your question answered?

**Comment by haomingli2020** [comment]
Closing the issue as there hasn't been new request for months. Feel free to reopen if you have more questions
