### ISSUE TITLE
Chat Widget State is wrong after ending a chat. 

### ISSUE THREAD

**Issue by coronel08** [amazon-connect/amazon-connect-chat-ui-examples#73]
On load the chat widget is working as desired. 

We have the `chat widget` icon showing when the chat window is not showing.
![Chat Widget Icon](https://user-images.githubusercontent.com/36834979/200136182-e9375d0a-9c7e-46a9-bb3c-c6bd02b95cf0.png)

We have the `chat minimize` arrow icon showing when the chat window is showing. 
![Chat minimize Arrow](https://user-images.githubusercontent.com/36834979/200136196-472e9a79-f60e-4e7a-bee3-a2f06b289d3a.png)

When we end a chat the widget state is in reverse order meaning that the showWidget states become wrong once we end a chat. 
![Ending Chat](https://user-images.githubusercontent.com/36834979/200136375-3bfc6062-8ef7-4707-b874-8cd7b8ac4747.png)

![Wrong Widget 1](https://user-images.githubusercontent.com/36834979/200136392-7049dcb5-6e15-4853-ac01-e0e8f3e319d7.png)

![Wrong Widget 2](https://user-images.githubusercontent.com/36834979/200136393-2c14ba08-c194-4b32-a8b3-188f5682489f.png)

**Comment by spencerlepine** [comment]
Hi @coronel08, thank you for taking the time to raise this issue.

Team is working on fix, pull request has been raised: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/123

Was able to reproduce and mitigate this issue:

## BEFORE

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/60903378/1db44801-7174-4e13-9484-5ce80175bcbc

## AFTER

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/60903378/c9b35855-1f8d-4669-8112-b590726d7844
