### ISSUE TITLE
Chat Widget Notifications Icon when message is received and chat window is minimized

### ISSUE THREAD

**Issue by coronel08** [amazon-connect/amazon-connect-chat-ui-examples#74]
https://docs.aws.amazon.com/connect/latest/adminguide/browser-notifications-chat.html

The feature for displaying a marker for unread messages above the widget does not seem to be included in this chat widget implementation. The website states 
"
Customers also receive a notification icon—a red dot—on the chat widget when it is minimized. The following image shows an image of the notification icon that customers receive when their chat window is minimized.
"
Image example below 
<img width="129" alt="chatwidget-browser-notification" src="https://user-images.githubusercontent.com/36834979/200137029-5a213334-836e-4669-92e3-18cc95beb630.png">

**Comment by haomingli2020** [comment]
Hi, the browser notification is not supported out-of-the-box today in this repo. But it's supported in our OOTB hosted widget which is the one in the link your shared.
Can you help us understand your use case? What's blocking you from using the hosted chat widget?

**Comment by coronel08** [comment]
I had to do some extra behavior to satisfy the clients needs. This meant customizing the Chat UI completely, changing the behavior of certain messages when incoming, and some other requests that i would not have been able to do with the Out of the box solution. While I was looking at incoming payload I decided to add browser notifications on incoming messages.

**Comment by spencerlepine** [comment]
Hi coronel08, thank you for taking the time to raise this issue. At this time the team is not actively adding new features to the `customChatWidget` code, and we are only maintaining the example functionality.

The intent of this ui-example code is to provide a reference for custom builders that are looking to extend functionality of the chat widget. We cannot support and maintain every feature request unfortunately.

As mentioned earlier, for the OOTB Amazon Connect Hosted Chat Widget, we currently support browser notifications. This is noted in the [official documentation](https://docs.aws.amazon.com/connect/latest/adminguide/browser-notifications-chat.html). Also planning to add a note to the Chat Interface open source code [README](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/spenlep/improve-readme-documentation/.github/docs/BrowserNotificationsFeature.md)

Going to close this issue as the team is not planning to take further action item. Please feel free to reach out with other question/issues that arise.

Thanks,
Spencer
