### ISSUE TITLE
Chat Initialization fails for same participant

### ISSUE THREAD

**Issue by ajmsra** [amazon-connect/amazon-connect-chat-ui-examples#8]
When a user has interacted once and his chat is closed, if he tries to reconnect with the same `First Name` and `Username` I am seeing below error in the browser console. The page is stuck at "Loading" and chat never starts. I tried giving all the roles "Administrator" access that are deployed. But still seeing this error

```
passing chat details to create: {"username":"jane111","instanceId":"<hidden>","previousContactId":"INITIAL_CHAT","startChatResult":{"ContactId":"9512d7bf-612e-4f1e-8b46-887859e7f963","ParticipantId":"49bfcdff-4abf-4974-8431-52dfc45f7d6b","ParticipantToken":"hidden"}} amazon-connect-chat-interface.js:1:1539326
in open chat session. need to connect amazon-connect-chat-interface.js:1:1541737
initiating websocket connection amazon-connect-chat-interface.js:1:1539532
unsuccessful connection {"_debug":{"reason":"Failed to fetch connectionDetails with createParticipantConnection","_debug":{"message":"Access denied","code":"AccessDeniedException","time":"2020-03-06T18:20:13.152Z","requestId":"17a6b48d-71ab-4f90-9f60-0d13b1e1c9ef","statusCode":403,"retryable":false,"retryDelay":60.40873616985627}},"connectSuccess":false,"connectCalled":true,"metadata":null} amazon-connect-chat-interface.js:1:1541999
initiateChat failure1 amazon-connect-chat-interface.js:1:1571120
failed 
Object { _debug: {…}, connectSuccess: false, connectCalled: true, metadata: null }
```

**Comment by efh365** [comment]
Hi ajmsra, Im not sure why you are in this state. It is interesting that you are getting an AccessDeniedException. When you look at the DDB, does it show an active conversation for the entry with the firstname + username? if so, this means the function that is supposed to update the DDB at the end of the chat did not work properly. I would look at the logs for that function to see what it is not properly ending the chat.

**Comment by ajmsra** [comment]
@efh365 yes it seems like, dynamo DB table is not getting updated when the chat ends, because of which the conversation is still active and hence that error.

I was looking at the logs for this function
**initiateChatLambda-** and it seems fine and do not see any errors
Can you please point me to the code in the lambda function which is s

**Comment by efh365** [comment]
Make sure the S3 trigger is set up properly. When the chat ends, the transcript should be uploaded to S3 and that triggers an update to DDB to mark the conversation as ended.

**Comment by ajmsra** [comment]
yes, it looks like `UpdateDdbWithS3LocationLambda` was never triggered, even though I see objects inside the bucket which holds ChatTranscripts.

**Comment by ajmsra** [comment]
after removing prefix from S3 trigger it is working fine now, thank you for your help

**Comment by dbasak-chat** [comment]
We had to delete the existing trigger and recreate it to make it work. This can also be a potential solution.
