### ISSUE TITLE
asyncCustomChatUX----After Click End Chat Button Screen Requires Refreshing otherwise chat initialiazation failed #16

### ISSUE THREAD

**Issue by kedasikumar** [amazon-connect/amazon-connect-chat-ui-examples#85]
Hi @angieyu,
   1. For the first time if you run CMD prompt for Customer Side then it's showing Chat Window. Then if we select Chat or Video option further then it's not responding to any of this option. 

Attaching the har capture screenshot for reference.

Please let me know on how to proceed further on this.

NOTE: <img width="614" alt="CustomerChat" src="https://user-images.githubusercontent.com/122768957/212612275-c2b7b4f2-a2ce-4d40-a849-fc6a13ffea90.png">

   2. I am facing a similar issue when trying to initialize the Chat widget on the customer application end. The DynamoDb table does not get updated when a new chat is initiated after ending the previous chat. This makes use of the same Participant token leading to a 403 Access Denied error.

Attaching the har capture screenshot for reference.

Please let me know on how to proceed further on this.

NOTE: <img width="677" alt="CustomerErro" src="https://user-images.githubusercontent.com/122768957/212612383-4dd0dd62-3c71-452e-a456-509b9e4b3cce.png">

**Comment by jiahaoyu6666** [comment]
Hi @kedasikumar, asyncCustomChatUX approach will be deprecated soon, please take a look at the startChatContactAPI approach. You can enable persistent chat feature in this approach. It is the same feature in asyncCustomChatUX. Learn more about persistent chat: https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html

**Comment by chaumdh** [comment]
Hi @kedasikumar, 

1. For interactive messages with Lex bot, we currently support List picker, List picker with images, and Time picker. For other custom configuration with Lex bot, you can check out this guide [Amazon Lex
V2 Developer Guide](https://docs.aws.amazon.com/lexv2/latest/dg/lambda.html) Depending on your intended use case, you will need to set up a Lambda function to specify what action the bot needs to take depends on the user input and associate that Lambda function with your bot, or you can add code to check for user inputs and give system responses.

2. As @jiahaoyu6666 mentioned, please follow [startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI) approach as our asyncCustomChatUX approach will be deprecated soon.
