### ISSUE TITLE
customChatWidget initiating multiple chats/contactIDs

### ISSUE THREAD

**Issue by niydt** [amazon-connect/amazon-connect-chat-ui-examples#94]
Using the default sample code provided for customChatWidget, Front end code is initiating multiple chat request to the API Gateway backend. Please note that the initial form/chat submission only calls the backend API gateway once, however all subsequent chats created invokes the create chat API multiple times unless the the window is refreshed everytime a chat ended. 

The current workflow is :

       Index.html ---> API Gateway ---> Lambda Function(StartChatContact)

**Comment by spencerlepine** [comment]
Closing issue, fix has been merged in: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/pull/96

Duplicate event handler triggers will be fix in latest bundle file: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/public/amazon-connect-chat-interface.js
